apiVersion: v2
name: helm-test-app
description: A Helm chart for deploying a bun application on Kubernetes
type: application
version: 1.0.0
appVersion: "1.16.0"
keywords:
  - nodejs
  - application
maintainers:
  - name: meru45
    email: mayur@scogo.ai
